[rewrite_local]
^https?://clientaccess\.10086\.cn/biz-orange/BN/userInformationService/getUserInformation url script-response-body https://github.com/Code-xy/cococo/raw/refs/heads/main/yidong_user.js

[mitm]
hostname = clientaccess.10086.cn
